### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ok-coder1** [kivy-garden/garden.circulardatetimepicker#11]
How do I install this?

**Comment by wishrohitv** [comment]
@ok-coder1 hey, i think is this code outdated and was written for python2 maybe,
here modified version you can use if you want - 
[circular_timer_picker.zip](https://github.com/kivy-garden/garden.circulardatetimepicker/files/14812262/circular_timer_picker.zip)

https://github.com/kivy-garden/garden.circulardatetimepicker/assets/126248971/43252aef-e7ae-42f2-8eb9-1d297a35074d

note - i'll not take warranty of my modified code

**Comment by ok-coder1** [comment]
Using KivyMD Time picker instead.
